### ISSUE TITLE
 设计页面拖入 arraytable 或者 arraycard 在预览页面会报错

### ISSUE THREAD

**Issue by linshuizhaoying** [trionesdev/triones-designable#14]
react-dom.development.js:26962 Uncaught TypeError: Cannot read properties of null (reading 'id')
    at useNodeIdProps2 (useNodeIdProps.js:11:1)
    at preview.tsx:38:18
    at observer.ts:31:34
    at Tracker2.track (tracker.ts:33:24)
    at useObserver (useObserver.ts:21:18)
    at wrappedComponent (observer.ts:31:16)
    at renderWithHooks (react-dom.development.js:15486:18)
    at updateFunctionComponent (react-dom.development.js:19617:20)
    at updateSimpleMemoComponent (react-dom.development.js:19454:10)
    at updateMemoComponent (react-dom.development.js:19303:14)

**Comment by fengxiaotx** [comment]
https://github.com/trionesdev/triones-designable/pull/15 大佬已亲自修复
